Make FIFO async iterable, add close() method
korkje/fifo pull request #1
Opened 2023-11-28 10:46 UTC by sgwilym

Hello! This is a pull request which makes `FIFO` asynchronously iterable, so you can do this: 

```ts
for await (const value of queue) {
	console.log(value);
}
```

Additionally, there is an extra `close` method added to the FIFO which allows you to signal that the queue is over and that any iterations should break.

The features can be completely ignored, and the FIFO can be used exactly the same way as before.

2023-11-28 17:24 UTC, korkje requested changes
Thanks for the PR! I very much like the idea of allowing for async iteration, the check for "end of queue" just needs to be fixed. The other stuff (`END`/`ERROR`, the `close` method and allowing `Promise<T>` to be pushed into the queue) I think should be left out of the implementation, and up to the user.

2023-11-28 17:24 UTC, korkje commented on lib/fifo.ts
> +export const ERROR = Symbol("Stream errored.");
Hmm, I'm not quite sure about these. I guess for convenience these are nice to have in some use cases, but I think it makes more sense to leave it out of the implementation and up to usage. I.e., users could create symbols like these themselves and check for them while iterating.

2023-11-28 17:24 UTC, korkje commented on lib/fifo.ts
> +export type Enqueueable<T> = T | Promise<T> | typeof END | typeof ERROR;
Allowing `Promise<T>` to be queued might lead a user to think the queue will spit out the resolved value, which it won't. I think this should also just be left up to usage, i.e. not including `Promise<T>` here, and rather let the user do something like `const fifo = new FIFO<number | Promise<number>>` themselves if they want to.

2023-11-28 17:35 UTC, korkje commented
Kind of ironic that I hadn't already thought of this, as I actually use this in the internal implementation of another project of mine that allows for async iteration of `WebSocket` messages.

2023-11-29 12:40 UTC, sgwilym commented
Yeah, those changes make sense to me too.

2023-12-11 22:42 UTC, merged